### ISSUE TITLE
/velt doesn't work unless `velt` is required

### ISSUE THREAD

**Issue by KikoPT1234** [Veltjs/Velt#17]
As the title says, if none of the scripts require the `velt` module, `./setup` isn't required either (according to @MrScopes), which causes the /velt command to never be loaded.

**Comment by MrScopes** [comment]
https://github.com/Veltjs/Velt/blob/main/src/main/resources/velt/index.js#L416
yeah it seems setup is required everytime velt is, I think it should be in velt loader

**Comment by Cormanz** [comment]
Prefered if you put issues/bugs on Guilded next time.

Nope, it shouldn't be in Velt-loader either, it needs to be required in load() like globals is

**Comment by Cormanz** [comment]
Fixed in a later commit but untested.

**Comment by Cormanz** [comment]
Should be fixed in a later commit.
